export { default as simplifyProcess } from './simplifyProcess' 
export { default as caputured } from './caputured' 
export { default as nestedHandler } from './nestedHandler' 
export { default as superSimplify } from './superSimplify' 
export { default as descartes } from './descartes' 
